// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyactznqztxbcbwaiknm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5YWN0em5xenR4YmNid2Fpa25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Mzk4NzgsImV4cCI6MjA3MjIxNTg3OH0.SFEwOZvG4mFWMIohvilA3vAFAD3dDLIaExE9ryUUS6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});