// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugioergsywxnqlcmqeun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnaW9lcmdzeXd4bnFsY21xZXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzODEyNDUsImV4cCI6MjA4ODk1NzI0NX0.CubSvJHayE784AiUw-lbWIgaUumD5ej164lT_fklZvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});